---
  # Открываем 443 порт
  - name: iptables HTTPS 443
    iptables:
      chain: INPUT
      protocol: tcp
      destination_port: 443
      jump: ACCEPT
    notify: save iptables
    tags: ["nginx", "iptables", "nginx_iptables", "le"]

  - name: Check exist certificate
    stat: "path={{ le_ssl_dir }}/{{ hostname }}.{{ domain_name }}/cert.pem"
    register: check_exist_cert_result
    tags: le, ssl-cert

  # Выполняем задачи получения сертификата
  - name: include Letsencrypt tasks
    include: getcert.yml
    when:
      (check_exist_cert_result.stat.exists == 0) or
      ( le_force_renew == 1)
    tags: le, ssl-cert